# Site wide configuration

title: Jaime Iniesta
locale: en_US
description: "I'm an independent Ruby on Rails consultant based in Girona, Spain, offering development, consultancy and mentoring services as part of the awesome ProRuby team.<br /><br /><small>You can <a href='mailto:jaimeiniesta@gmail.com'>hire me</a> for development, consultancy, code reviews and mentoring services.</small>"
logo: avatar_jaime_oxido_closeup.jpg
search: true
url: http://localhost:4000


# Jekyll configuration

permalink:   /articles/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Jaime Iniesta
  avatar: avatar_jaime_oxido_closeup.jpg
  email: jaimeiniesta@gmail.com
  disqus-shortname: jaimeiniesta
  twitter: jaimeiniesta
  facebook: jaime.iniesta.7
  github: jaimeiniesta
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: jaimeiniesta
  instagram: jaimeiniesta
  flickr: jaimeiniesta
  tumblr: #username
  google:
    plus: jaimeiniesta
    analytics: UA-415840-3
    verify:
    ad-client:
    ad-slot:
  bing-verify:
